"""Milestone 5 schema update

Revision ID: ded5b7d85f14
Revises: 5d4271d4981a
Create Date: 2026-07-23 22:47:08.734458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded5b7d85f14'
down_revision: Union[str, Sequence[str], None] = '5d4271d4981a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logs', sa.Column('qber', sa.Float(), nullable=True))
    op.add_column('auth_logs', sa.Column('authentication_result', sa.String(length=50), nullable=False))
    op.drop_column('auth_logs', 'event_type')
    op.drop_column('auth_logs', 'details')
    op.add_column('sessions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('protocol_version', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'protocol_version')
    op.drop_column('sessions', 'user_id')
    op.add_column('auth_logs', sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('auth_logs', sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('auth_logs', 'authentication_result')
    op.drop_column('auth_logs', 'qber')
    # ### end Alembic commands ###
