import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Button } from '@heroui/react';
import {
  ArrowRight, BookOpen, WaveSine, Key, Eye,
  GitBranch, Atom,
} from '@phosphor-icons/react';
import PageWrapper from '../components/shared/PageWrapper';
import SectionHeader from '../components/shared/SectionHeader';
import FAQAccordion from '../components/shared/FAQAccordion';
import BB84Timeline from '../components/features/bb84/BB84Timeline';
import ProtocolCard from '../components/features/bb84/ProtocolCard';
import BB84Workbench from '../components/features/bb84/workbench/BB84Workbench';
import ProtocolFacts from '../components/features/bb84/ProtocolFacts';
import { fadeInUp, fadeInRight, staggerContainer, defaultViewport } from '../utils/animations';

/* ─────────────────────────────────────────────────────── data ── */

const PROTOCOL_CARDS = [
  {
    step: 1, title: 'Bit Preparation',
    description: 'Alice generates a uniformly random sequence of classical bits (0s and 1s) using quantum randomness as the entropy source.',
    purpose: 'Provides unbiased raw material for key generation — impossible to predict or pre-compute.',
    implementationNote: 'Qiskit Sampler will generate quantum random bits via Hadamard circuits on IBM hardware.',
  },
  {
    step: 2, title: 'Basis Selection',
    description: 'Alice randomly selects an encoding basis (+ or ×) for each bit. The selection is uniformly random and independent per bit.',
    purpose: 'Dual-basis encoding creates the quantum uncertainty that makes BB84 secure against eavesdropping.',
    implementationNote: 'Basis selection will also be derived from quantum randomness via Qiskit circuits.',
  },
  {
    step: 3, title: 'Qubit Encoding',
    description: 'Alice maps each classical bit + basis pair onto a photon polarization state. Four distinct quantum states are used.',
    purpose: 'Physical encoding of information into quantum states whose measurement disturbs the original.',
    implementationNote: 'Quantum circuits with Hadamard and X gates simulate polarization encoding on simulator/hardware.',
  },
  {
    step: 4, title: 'Quantum Transmission',
    description: 'Encoded photons are sent through the quantum channel. The No-Cloning Theorem guarantees Eve cannot intercept without leaving a trace.',
    purpose: 'Establishes the quantum link between Alice and Bob with provable physical security guarantees.',
    implementationNote: 'Simulated quantum channel with configurable noise parameter in JavaScript engine; IBM hardware in M3.',
  },
  {
    step: 5, title: 'Bob\'s Measurement',
    description: 'Bob randomly measures each incoming photon in one of the two bases. Correct-basis measurements are always accurate; incorrect-basis results are random.',
    purpose: 'Bob\'s independent basis choices create the structure needed for secure key sifting.',
    implementationNote: 'Measurement outcomes generated by Qiskit circuit simulation with configurable QBER injection.',
  },
  {
    step: 6, title: 'Basis Sifting',
    description: 'Alice and Bob compare their basis sequences over a public classical channel. Bits with mismatched bases are discarded.',
    purpose: 'Retains ~50% of bits as the raw sifted key while ensuring both parties hold identical values.',
    implementationNote: 'Classical comparison handled by FastAPI endpoint; basis data exchanged via WebSocket in real time.',
  },
  {
    step: 7, title: 'Key Derivation',
    description: 'Remaining matched-basis bits form the sifted key. Privacy amplification via hashing reduces any partial information Eve may have obtained.',
    purpose: 'Produces the final shared secret key used as the authentication token.',
    implementationNote: 'HKDF-SHA256 privacy amplification applied server-side before token issuance.',
  },
  {
    step: 8, title: 'QBER Calculation',
    description: 'A random sample of sifted key bits is sacrificed and publicly compared. The error rate reveals whether an eavesdropper was present.',
    purpose: 'Quantifies channel noise and potential eavesdropping. Session is aborted if QBER ≥ 11%.',
    implementationNote: 'QBER displayed live in simulation panel; threshold check enforced by FastAPI backend logic.',
  },
  {
    step: 9, title: 'Authentication Decision',
    description: 'If QBER is within bounds, the shared key is accepted and an authentication token is issued. Otherwise the session is terminated.',
    purpose: 'Final security gate — ensures no authenticated session exists when quantum security is compromised.',
    implementationNote: 'Supabase session token issued on successful QBER check; JWT signed with derived key material.',
  },
];

const FAQ_ITEMS = [
  {
    question: 'What is the BB84 protocol?',
    answer:
      'BB84 is the first quantum key distribution protocol, proposed by Charles Bennett and Gilles Brassard at IBM Research in 1984. It uses the quantum properties of photons — specifically polarization states — to securely distribute cryptographic keys between two parties. Security is guaranteed by the laws of quantum mechanics, making it unconditionally secure against any computational attack.',
  },
  {
    question: "Why can't an eavesdropper intercept the key undetected?",
    answer:
      "Quantum mechanics dictates that measuring an unknown quantum state disturbs it. If Eve intercepts and measures Alice's photons, she collapses the quantum superposition and introduces errors in the states Bob receives. These errors manifest as an elevated QBER, alerting Alice and Bob to the intrusion. The No-Cloning Theorem additionally prevents Eve from copying qubits to measure later.",
  },
  {
    question: 'What is the QBER threshold and why is it ~11%?',
    answer:
      'The ~11% threshold is derived from information-theoretic security proofs. Below this error rate, the information Eve could have obtained is bounded and can be eliminated through privacy amplification. The exact threshold depends on the specific BB84 variant and privacy amplification scheme. Above 11%, Alice and Bob cannot guarantee the key remains secret and must abort.',
  },
  {
    question: 'What are the two bases used in BB84?',
    answer:
      'BB84 uses two conjugate (incompatible) bases. The rectilinear basis (+) encodes bit 0 as horizontal polarization and bit 1 as vertical polarization. The diagonal basis (×) encodes bit 0 as 45° polarization and bit 1 as 135° polarization. These bases are mutually unbiased — measuring in the wrong basis yields a completely random result, which is the foundation of BB84\'s security.',
  },
  {
    question: 'How does Qinert use BB84 for authentication?',
    answer:
      "Qinert extends BB84's key distribution property into authentication. The quantum-established shared secret serves as a one-time authentication token derived fresh for each session. Because the key is generated using quantum randomness and established through a quantum channel, it cannot be predicted, replayed, or stolen without quantum hardware access and the ability to defeat the QBER check.",
  },
  {
    question: 'Will this work on real IBM quantum hardware?',
    answer:
      'Yes. The Milestone 2 simulation engine will first implement BB84 in JavaScript for in-browser demonstration. Milestone 3 will connect to IBM Quantum Runtime via Qiskit, executing actual quantum circuits on IBM superconducting quantum processors. The current frontend is designed to seamlessly accommodate real hardware outputs with no UI changes.',
  },
];

/* ───────────────────────────────────────────────── component ── */

export default function BB84Explorer() {
  return (
    <PageWrapper>
      {/* ── HERO ──────────────────────────────────────────────────── */}
      <section className="pt-20 pb-20 px-6 border-b border-border-subtle relative overflow-hidden" aria-labelledby="bb84-hero-heading">
        {/* Background glow */}
        <div
          className="absolute inset-0 flex items-center justify-center pointer-events-none"
          aria-hidden="true"
        >
          <div className="w-[60vw] h-[60vw] bg-[radial-gradient(circle_at_center,rgba(15,98,254,0.07)_0%,rgba(138,63,252,0.03)_40%,transparent_70%)] rounded-full" />
        </div>

        <div className="max-w-5xl mx-auto relative z-10">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={staggerContainer}
            className="flex flex-col gap-6"
          >
            <motion.div variants={fadeInUp} className="flex items-center gap-3">
              <span className="text-xs font-mono text-text-muted/50 uppercase tracking-[0.2em]">
                Qinert /
              </span>
              <span className="inline-flex items-center gap-1.5 text-xs font-mono font-medium bg-primary-500/10 border border-primary-500/20 text-primary-400 px-2.5 py-1 rounded-sm">
                <Atom size={11} aria-hidden="true" />
                BB84 Quantum Key Distribution
              </span>
            </motion.div>

            <motion.h1
              id="bb84-hero-heading"
              variants={fadeInUp}
              className="text-5xl md:text-6xl lg:text-7xl font-semibold tracking-tight text-text-main leading-[1.08]"
            >
              Explore the{' '}
              <span className="text-transparent bg-clip-text bg-linear-to-r from-primary-400 to-secondary-400">
                BB84 Protocol
              </span>
            </motion.h1>

            <motion.p
              variants={fadeInUp}
              className="text-lg md:text-xl text-text-muted max-w-2xl leading-relaxed"
            >
              Understand every step of quantum key distribution — from photon encoding to
              eavesdropping detection. The interactive timeline walks through all nine phases of
              the protocol that underpins Qinert authentication.
            </motion.p>

            <motion.div variants={fadeInUp} className="flex flex-col sm:flex-row gap-3 pt-2">
              <Button
                as={Link}
                to="/documentation"
                size="lg"
                className="bg-primary-500 hover:bg-primary-400 text-white font-medium rounded-sm px-8 transition-all hover:shadow-[0_0_24px_rgba(15,98,254,0.35)]"
                startContent={<BookOpen size={17} aria-hidden="true" />}
              >
                Read Documentation
              </Button>
              <Button
                as={Link}
                to="/authenticate"
                size="lg"
                variant="bordered"
                className="border-border-subtle text-text-main font-medium rounded-sm px-8 hover:bg-surface hover:border-primary-700/50 transition-all"
                endContent={<ArrowRight size={17} aria-hidden="true" />}
              >
                Start Authentication
              </Button>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* ── INTERACTIVE TIMELINE ──────────────────────────────────── */}
      <section className="py-24 px-6" aria-labelledby="timeline-heading">
        <div className="max-w-5xl mx-auto">
          <SectionHeader
            label="Interactive Timeline"
            title="The Nine Phases of BB84"
            subtitle="Click any step to explore its role in the quantum key distribution protocol."
          />
          <BB84Timeline />
        </div>
      </section>

      {/* ── PROTOCOL OVERVIEW ─────────────────────────────────────── */}
      <section className="py-24 px-6 bg-surface/20 border-y border-border-subtle" aria-labelledby="overview-heading">
        <div className="max-w-6xl mx-auto">
          <SectionHeader
            label="Protocol Overview"
            id="overview-heading"
            title="Understanding BB84"
            subtitle="The science behind quantum key distribution and why it offers unconditional security."
          />

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
            {/* Left: concept cards */}
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={defaultViewport}
              variants={staggerContainer}
              className="flex flex-col gap-5"
            >
              {[
                {
                  icon: WaveSine,
                  title: 'Quantum Key Distribution',
                  body: 'QKD uses quantum mechanical properties to produce and distribute a shared cryptographic key. Unlike classical key exchange, its security is based on physics, not computational hardness assumptions.',
                },
                {
                  icon: GitBranch,
                  title: 'Conjugate Bases',
                  body: 'BB84 encodes information in two incompatible (conjugate) bases. Measuring in the wrong basis yields a random result with no information — this incompatibility is the root of the protocol\'s security.',
                },
                {
                  icon: Eye,
                  title: 'Eavesdropping Detection',
                  body: 'Any interception of photons collapses their quantum state, introducing detectable errors. The QBER check quantifies these errors — a rate above ~11% conclusively indicates an eavesdropper.',
                },
                {
                  icon: Key,
                  title: 'Shared Secret',
                  body: 'After sifting and privacy amplification, both parties hold an identical key derived from quantum randomness. This key is provably secret — information-theoretically, not computationally.',
                },
              ].map(({ icon: Icon, title, body }, idx) => (
                <motion.div key={idx} variants={fadeInUp} className="flex gap-4">
                  <div className="w-9 h-9 rounded-sm bg-surface border border-border-subtle flex items-center justify-center shrink-0 mt-0.5">
                    <Icon size={18} className="text-primary-400" aria-hidden="true" />
                  </div>
                  <div>
                    <h3 className="font-medium text-text-main mb-1.5">{title}</h3>
                    <p className="text-sm text-text-muted leading-relaxed">{body}</p>
                  </div>
                </motion.div>
              ))}
            </motion.div>

            {/* Right: visual encoding diagram */}
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={defaultViewport}
              variants={fadeInRight}
              className="quantum-card rounded-sm border border-border-subtle p-8"
            >
              <p className="text-xs font-mono text-text-muted/50 uppercase tracking-wider mb-6">
                Encoding Reference
              </p>
              <div className="space-y-6">
                {[
                  {
                    basis: 'Rectilinear (+)',
                    rows: [
                      { bit: '0', symbol: '|→⟩', label: 'Horizontal', color: 'text-primary-400' },
                      { bit: '1', symbol: '|↑⟩', label: 'Vertical', color: 'text-primary-400' },
                    ],
                  },
                  {
                    basis: 'Diagonal (×)',
                    rows: [
                      { bit: '0', symbol: '|↗⟩', label: '45° diagonal', color: 'text-secondary-400' },
                      { bit: '1', symbol: '|↘⟩', label: '135° diagonal', color: 'text-secondary-400' },
                    ],
                  },
                ].map(({ basis, rows }) => (
                  <div key={basis}>
                    <p className="text-xs font-mono text-text-muted/60 mb-3">{basis}</p>
                    <div className="space-y-2">
                      {rows.map(({ bit, symbol, label, color }) => (
                        <div key={bit} className="flex items-center gap-4 p-3 bg-background-main/40 border border-border-subtle rounded-sm">
                          <span className="text-xs font-mono text-text-muted/50 w-10">Bit {bit}</span>
                          <span className={`font-mono font-bold text-lg w-10 ${color}`}>{symbol}</span>
                          <span className="text-xs text-text-muted">{label}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ── PROTOCOL DETAIL CARDS ─────────────────────────────────── */}
      <section className="py-24 px-6" aria-labelledby="detail-cards-heading">
        <div className="max-w-6xl mx-auto">
          <SectionHeader
            label="Protocol Stages"
            id="detail-cards-heading"
            title="Each Phase in Detail"
            subtitle="How every stage connects and what Milestone 2 will add."
          />
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {PROTOCOL_CARDS.map((card, idx) => (
              <ProtocolCard key={idx} {...card} delay={idx * 0.04} />
            ))}
          </div>
        </div>
      </section>

      {/* ── SIMULATION WORKBENCH ────────────────────────────────── */}
      <section className="py-24 px-6 bg-surface/20 border-y border-border-subtle" aria-labelledby="sim-heading">
        <div className="max-w-7xl mx-auto">
          <SectionHeader
            label="Simulation Engine"
            id="sim-heading"
            title="Interactive Workbench"
            subtitle="Step through the protocol phases. Live simulation logic will be available in Milestone 2."
            centered
          />
          <BB84Workbench steps={PROTOCOL_CARDS} />
        </div>
      </section>

      {/* ── PROTOCOL FACTS ────────────────────────────────────────── */}
      <section className="py-24 px-6" aria-labelledby="facts-heading">
        <div className="max-w-6xl mx-auto">
          <SectionHeader
            label="Protocol Reference"
            id="facts-heading"
            title="BB84 Facts"
            subtitle="Key facts about the BB84 protocol — all factually verified."
          />
          <ProtocolFacts />
        </div>
      </section>

      {/* ── FAQ ───────────────────────────────────────────────────── */}
      <section className="py-24 px-6 bg-surface/20 border-y border-border-subtle" aria-labelledby="faq-heading">
        <div className="max-w-3xl mx-auto">
          <SectionHeader
            label="FAQ"
            id="faq-heading"
            title="Common Questions"
            subtitle="Frequently asked questions about BB84, QKD, and Qinert."
          />
          <FAQAccordion items={FAQ_ITEMS} />
        </div>
      </section>

      {/* ── CTA ───────────────────────────────────────────────────── */}
      <section className="py-32 px-6 relative overflow-hidden" aria-labelledby="cta-heading">
        <div
          className="absolute inset-0 flex items-center justify-center pointer-events-none"
          aria-hidden="true"
        >
          <div className="w-[50vw] h-[50vw] bg-[radial-gradient(circle_at_center,rgba(15,98,254,0.1)_0%,rgba(138,63,252,0.04)_50%,transparent_70%)] rounded-full" />
        </div>

        <div className="max-w-3xl mx-auto text-center relative z-10 flex flex-col items-center gap-6">
          <motion.h2
            id="cta-heading"
            initial="hidden"
            whileInView="visible"
            viewport={defaultViewport}
            variants={fadeInUp}
            className="text-4xl md:text-5xl font-semibold tracking-tight leading-tight"
          >
            Ready to go deeper?
          </motion.h2>
          <motion.p
            initial="hidden"
            whileInView="visible"
            viewport={defaultViewport}
            variants={fadeInUp}
            className="text-lg text-text-muted max-w-xl"
          >
            Explore the complete technical documentation or begin the authentication flow.
          </motion.p>
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={defaultViewport}
            variants={fadeInUp}
            className="flex flex-col sm:flex-row gap-3"
          >
            <Button
              as={Link}
              to="/documentation"
              size="lg"
              className="bg-primary-500 hover:bg-primary-400 text-white font-medium rounded-sm px-8 transition-all hover:shadow-[0_0_24px_rgba(15,98,254,0.35)]"
              startContent={<BookOpen size={17} aria-hidden="true" />}
            >
              Read Documentation
            </Button>
            <Button
              as={Link}
              to="/authenticate"
              size="lg"
              variant="bordered"
              className="border-border-subtle text-text-main font-medium rounded-sm px-8 hover:bg-surface transition-all"
              endContent={<ArrowRight size={17} aria-hidden="true" />}
            >
              Start Authentication
            </Button>
          </motion.div>
        </div>
      </section>
    </PageWrapper>
  );
}
